app/forms/admin_create_user.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, IntegerField
from wtforms.validators import InputRequired, Length, Email, ValidationError
from app.models import users

class AdminCreateUserForm(FlaskForm):
    login_name = StringField('Login Name', validators=[InputRequired(), Length(min=1, max=50)])
    first_name = StringField('First Name', validators=[InputRequired(), Length(min=1, max=100)])
    last_name = StringField('Last Name', validators=[InputRequired(), Length(min=1, max=100)])
    university_number = StringField('University Number', validators=[InputRequired(), Length(min=1, max=20)])
    university_email = StringField('University Email', validators=[InputRequired(), Email(), Length(min=1, max=225)])
    program = StringField('Program', validators=[Length(max=100)])
    password = PasswordField('Password', validators=[InputRequired(), Length(min=1, max=100)])
    account_status = IntegerField("Account Type [1:ADMIN, 2:TUTOR, 3:STUDENT/TUTEE]", validators=[InputRequired()])
    create_user = SubmitField('Create User')


    #perform checks if the login_name and email already exist in the database
    def validate_login_name(self, field):
        if users.Users.is_login_name_taken(field.data):
            raise ValidationError('This Login Name is already taken. Please choose another one or Login.')
        
    def validate_university_email(self, field):
        if users.Users.is_university_email_taken(field.data):
            raise ValidationError('This email is already registered. Please use a different email address or Login.')

app/forms/edit_profile_form.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, IntegerField, SelectField
from wtforms.validators import InputRequired, Length, Email, ValidationError
from app.models import users

class EditProfile(FlaskForm):
    login_name = StringField('Login Name', validators=[InputRequired(), Length(min=1, max=50)])
    first_name = StringField('First Name', validators=[InputRequired(), Length(min=1, max=100)])
    last_name = StringField('Last Name', validators=[InputRequired(), Length(min=1, max=100)])
    university_number = StringField('University Number', validators=[InputRequired(), Length(min=1, max=20)])
    university_email = StringField('University Email', validators=[InputRequired(), Email(), Length(min=1, max=225)])
    program = StringField('Program', validators=[Length(max=100)])
    password = PasswordField('Password', validators=[Length(min=0, max=100)])
    tags = StringField('Tags', validators=[Length(max=100)])
    account_status = SelectField("Account Type", choices=[(1, "ADMIN"), (2, "TUTOR"), (3, "STUDENT")])
    edit_user = SubmitField('APPLY CHANGES')

app/forms/login.py
from flask_wtf import FlaskForm
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import InputRequired, Length, ValidationError
from app.models import users
from app.extensions import bcrypt

class LoginForm(FlaskForm):
    login_name = StringField("Login Name", validators=[InputRequired(), Length(min=1, max=50)])
    password = PasswordField("Password", validators=[InputRequired(), Length(min=1, max=100)])
    login = SubmitField("LOGIN")

app/forms/registration.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import InputRequired, Length, Email, ValidationError
from app.models import users

class RegistrationForm(FlaskForm):
    login_name = StringField('Login Name', validators=[InputRequired(), Length(min=1, max=50)])
    first_name = StringField('First Name', validators=[InputRequired(), Length(min=1, max=100)])
    last_name = StringField('Last Name', validators=[InputRequired(), Length(min=1, max=100)])
    university_number = StringField('University Number', validators=[InputRequired(), Length(min=1, max=20)])
    university_email = StringField('University Email', validators=[InputRequired(), Email(), Length(min=1, max=225)])
    program = StringField('Program', validators=[Length(max=100)])
    password = PasswordField('Password', validators=[InputRequired(), Length(min=1, max=100)])
    register = SubmitField('Register')

    #perform checks if the login_name and email already exist in the database
    def validate_login_name(self, field):
        if users.Users.is_login_name_taken(field.data):
            raise ValidationError('This Login Name is already taken. Please choose another one or Login.')
        
    def validate_university_email(self, field):
        if users.Users.is_university_email_taken(field.data):
            raise ValidationError('This email is already registered. Please use a different email address or Login.')

app/routes/auth.py
from flask import Blueprint, render_template, redirect, url_for, flash
from app.forms.login import LoginForm
from wtforms.validators import ValidationError as WTFormsValidationError  # Rename to avoid confusion
from app.models import users
from app.extensions import bcrypt, db, login_manager
from flask_login import login_user, logout_user, current_user

authentication = Blueprint("authentication", __name__, template_folder="app/templates", static_folder="app/static")

@authentication.route("/login", methods=['POST', 'GET'])
def login():
    # checks if user is already logged in
    if current_user.is_authenticated:
        return redirect(url_for('home.home'))
    
    form = LoginForm()

    if form.validate_on_submit():
        print("valid")
        login_name = form.login_name.data
        password = form.password.data
        user = users.Users.query.filter_by(login_name=login_name).first()

        if user:
            try:
                if bcrypt.check_password_hash(user.password, password):
                    login_user(user)
                    return redirect(url_for('home.home'))
                else:
                    flash("Invalid Username or password!", "danger")
            except Exception as e:
                flash(e, "danger")
        else:
            flash("User Does Not Exist.", "danger")

    return render_template("login.html", form=form)

@authentication.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('authentication.login'))

app/routes/edit_profile.py
from flask import Blueprint, render_template, redirect, url_for, flash
from app.extensions import db, bcrypt
from app.forms import edit_profile_form
from app.models import users, activity_logs, sessions
from wtforms.validators import ValidationError as WTFormsValidationError  # Rename to avoid confusion
from flask_login import current_user, login_required
from datetime import datetime, timedelta


edit_profile_route = Blueprint("edit_profile", __name__, template_folder="app/templates", static_folder="app/static")

@edit_profile_route.route('/edit/profile', methods=['GET', 'POST'])
@login_required
def edit_profile():
    user=users.Users.query.get(current_user.id)
    user_password = user.password
    form = edit_profile_form.EditProfile(obj=user)
    check_form = form.validate_on_submit()
    
    if check_form:
        form.populate_obj(user)
        new_password = form.password.data
        if new_password:  # Check if new password is provided
            hashed_password = bcrypt.generate_password_hash(new_password).decode('utf-8')
            user.password = hashed_password
        # No need for an "else" statement here; if new_password is empty, it won't update the password
        else:
            user.password = user_password
        db.session.commit()
        flash('Profile information updated successfully', 'success')
        return redirect(url_for('edit_profile.edit_profile')) 

    return render_template("edit_profile.html", form=form)

app/routes/register.py
from flask import Blueprint, render_template, redirect, url_for, flash
from app.forms import registration
from app.extensions import db, bcrypt
from app.forms.admin import admin_create_user
from app.models import users
from wtforms.validators import ValidationError as WTFormsValidationError  # Rename to avoid confusion
from flask_login import current_user


registration_route = Blueprint("registration", __name__, template_folder="app/templates", static_folder="app/static")

# simple account creation
@registration_route.route("/registration", methods = ["POST", "GET"])
def register():
    # checks if user is already logged in
    if current_user.is_authenticated:
        return redirect(url_for('home.home'))
    
    form = registration.RegistrationForm()
    check_form = form.validate_on_submit()
    print(check_form)
    if check_form:
        print("test")
        login_name = form.login_name.data
        university_email = form.university_email.data
        try:
            password = bcrypt.generate_password_hash(form.password.data)
            new_user = users.Users(
                login_name=login_name.lower(),
                first_name=form.first_name.data,
                last_name=form.last_name.data,
                university_number=form.university_number.data,
                university_email=university_email,
                program=form.program.data,
                password=password,
                account_status=3,  # default for creating a student account (tutee)
                tags="",
                #profile_pic=""
            )

            db.session.add(new_user)
            db.session.commit()
            
            flash('Account Created', 'Success')
            return redirect(url_for("authentication.login"))

        
        except Exception as e:
            flash(str(e), 'ERROR')
            db.session.rollback()
    else:
        print("error")
        try:
            login_name = form.login_name.data
            university_email = form.university_email.data
            form.validate_login_name(form.login_name)
            form.validate_university_email(form.university_email)
        except WTFormsValidationError as e:
            flash(str(e))


    return render_template("registration.html", form=form)

app/templates/admin_create_user.html
{% extends 'base.html' %}
{% block main %}
<!--
{% with messages = get_flashed_messages() %}
{% if messages %}
{% for message in messages %}
<div class="alert alert-danger" role="alert">
  {{message}}
</div>
{% endfor %}
{% endif %}
{% endwith %}
-->
<div class="main-container">
  <h1>CREATE USER</h1>
  <div class="circle"></div>
  <form method="POST" action="{{ url_for('admin_creation_route.create_user') }}">
    <div class="form-container">

      {{ form.hidden_tag() }}

      <!-- Two columns for form fields -->
      <div class="columns">
        <div class="column">
          <div class="input-group">
            <span class="input-label">LOGIN NAME:</span>
            {{ form.login_name(size=35, class="form-control", placeholder="ENTER LOGIN NAME") }}
          </div>

          <div class="input-group">
            <span class="input-label">FIRST NAME:</span>
            {{ form.first_name(size=35, class="form-control", placeholder="ENTER FIRST NAME") }}
          </div>

          <div class="input-group">
            <span class="input-label">LAST NAME:</span>
            {{ form.last_name(size=35, class="form-control", placeholder="ENTER LAST NAME") }}
          </div>

          <div class="input-group">
            <span class="input-label">UNIVERSITY NUMBER:</span>
            {{ form.university_number(size=35, class="form-control", placeholder="ENTER UNIVERSITY NUMBER") }}
          </div>
        </div>

        <div class="column">
          <div class="input-group">
            <span class="input-label">PROGRAM/ROLE:</span>
            {{ form.program(size=35, class="form-control", placeholder="ENTER PROGRAM") }}
          </div>

          <div class="input-group">
            <span class="input-label">UNIVERSITY EMAIL:</span>
            {{ form.university_email(size=35, class="form-control", placeholder="ENTER EMAIL") }}
          </div>

          <div class="input-group">
            <span class="input-label">ACCOUNT TYPE:</span>
            {{ form.account_status(class="form-control", style="background-color: #C4B381; font-weight: bold;") }}
          </div>

          <div class="input-group">
            <span class="input-label">PASSWORD:</span>
            {{ form.password(size=35, class="form-control", placeholder="ENTER PASSWORD", type="password") }}
          </div>
        </div>
      </div>
    </div>
    <div class="btn-group">
      {{ form.create_user(size=20, class="btn btn-success", type="submit", style="font-weight: bold;")}}
      <button class="btn-cancel" id="cancel-btn" style="font-weight: bold;">CANCEL</button>

    </div>

  </form>
</div>


<style>
  body {
    background-color: #FFF6DD;
  }

  .main-container {
    text-align: center;
    padding: 10px;
  }

  .form-container {
    max-width: 1000px;
    padding: 50px;
    font-family: Montserrat;
    margin: 0 auto;
    padding: 20px;
    background-color: #E8DFC7;
    box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    border-radius: 5px;
  }

  .circle {
    width: 100px;
    height: 100px;
    background-color: #ccc;
    border-radius: 50%;
    margin: 0 auto;
    /* Center horizontally */
  }

  h1 {
    font-size: 24px;
    margin-bottom: 20px;
    justify-content: center;
    font-weight: bold;
  }


  form {
    margin: 20px;
  }

  label {
    font-weight: bold;
  }

  .btn-success {
    background-color: #5A110C;
    color: #fff;
    border: none;
    padding: 20px;
    border-radius: 10px;
    cursor: pointer;
    font-size: 16px;
    min-width: 200px
  }

  .btn-cancel {
    background-color: #371513;
    color: #fff;
    border: none;
    padding: 20px;
    border-radius: 10px;
    cursor: pointer;
    font-size: 16px;
    min-width: 200px
  }

  .btn-group {
    margin-top: 20px;
  }

  .alert {
    background-color: #f8d7da;
    color: #721c24;
    padding: 10px;
    margin-top: 10px;
    border-radius: 4px;
  }

  .alert-danger {
    border: 1px solid #f5c6cb;
  }

  /* Style the input group to display the label and input field together */
  .input-group {
    display: flex;
    align-items: center;
    margin-bottom: 10px;
    padding: 1px;
    background-color: #F5F5F5;
    border-radius: 10px;

  }

  /* Style the label within the input group */
  .input-label {
    flex: 0 0 150px;
    /* Adjust the width as needed */
    font-weight: bold;
    margin-right: 10px;
    color: #A5A5A5;
  }

  /* Style the input field within the input group */
  .form-control {
    flex: 1;
    min-width: 100px;
    padding: 20px;
    border-radius: 8px;
    border: none;
    font-size: 16px;
    text-align: left;
    background-color: #F5F5F5;
  }

  /* Style the placeholder text */
  .form-control::placeholder {
    color: #A5A5A5;
    font-weight: normal;
    /* Remove bold styling for placeholder */
  }

  .columns {
    display: flex;
    justify-content: space-between;
  }

  .column {
    flex: 1;
    margin-right: 20px;
  }

  @media (max-width: 768px) {
    * {
      transform: scale(0.9);
      font-family: Montserrat;

    }
  }
</style>
<script>

  const cancelBTN = document.getElementById("cancel-btn");

  cancelBTN.onclick = function () {
    location.href = "{{ url_for('admin_redirects.manage_users') }}"
  }
</script>

{% endblock %}

app/templates/admin_manage_applications.html
{% extends 'base.html' %}
{% block main %}


<div class="main-container">
    <h1>TUTOR APPLICATION</h1>
    <div class="circle-edit-profile"></div>
    <h2> {{ application_information[0].student.first_name}} {{ application_information[0].student.last_name}}</h2>
    <div class="form-container">

        <!-- Two columns for form fields -->

        <div class="columns">
            <div class="column">
                <div class="input-group">
                    <div class="input-label">
                        UNIVERSITY NUMBER:
                    </div>
                    <div class="form-control">
                        {{ application_information[0].student.university_number}}
                    </div>
                </div>

                <div class="input-group">
                    <div class="input-label">
                        UNIVERSITY EMAIL:
                    </div>
                    <div class="form-control">
                        {{ application_information[0].student.university_email}}
                    </div>
                </div>

                <div class="input-group">
                    <div class="input-label">
                        PROGRAM:
                    </div>
                    <div class="form-control">
                        {{ application_information[0].student.program}}
                    </div>
                </div>
            </div>

            <!--column 2-->
            <div class="column">
                <div class="input-group">
                    <div class="form-control">
                        {{ application_information[0].description}}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="btn-group">
        <button class="btn-success" id="cancel-btn" style="font-weight: bold;">ACCEPT</button>
        <button class="btn-cancel" id="cancel-btn" style="font-weight: bold;">CANCEL</button>

    </div>
</div>


<style>
    body {
        background-color: #FFF6DD;
    }

    .alert-container {
        display: flex;
        flex-direction: column;
        align-items: center;
    }

    .alert {
        width: 80%;
        max-width: 500px;
        /* Adjust as needed */
        margin: 10px 0;
        padding: 20px;
        border-radius: 5px;
        text-align: center;
    }

    .alert.success {
        background-color: #54F47D;
        /* Green color for success */
        color: white;
    }

    .closebtn {
        cursor: pointer;
        float: right;
        font-size: 20px;
        margin-left: 10px;
    }

    .main-container {
        text-align: center;
        padding: 10px;
    }

    .form-container {
        max-width: 1200px;
        padding: 50px;
        font-family: Montserrat;
        margin: 0 auto;
        padding: 20px;
        background-color: #E8DFC7;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        border-radius: 5px;
        display: flex;
        flex-direction: column;
    }

    .circle-edit-profile {
        width: 100px;
        height: 100px;
        background-color: #ccc;
        border-radius: 50%;
        margin: 0 auto;
        /* Center horizontally */
    }

    h1 {
        font-size: 24px;
        margin-bottom: 20px;
        justify-content: center;
        font-weight: bold;
    }


    form {
        margin: 20px;
    }

    label {
        font-weight: bold;
    }

    .btn-success {
        background-color: #006400;
        color: #fff;
        border: none;
        padding: 20px;
        border-radius: 10px;
        cursor: pointer;
        font-size: 16px;
        min-width: 200px
    }

    .btn-cancel {
        background-color: #371513;
        color: #fff;
        border: none;
        padding: 20px;
        border-radius: 10px;
        cursor: pointer;
        font-size: 16px;
        min-width: 200px
    }

    .btn-group {
        margin-top: 20px;
    }

    .alert {
        background-color: #f8d7da;
        color: #721c24;
        padding: 10px;
        margin-top: 10px;
        border-radius: 4px;
    }

    .alert-danger {
        border: 1px solid #f5c6cb;
    }

    /* Style the input group to display the label and input field together */
    .input-group {
        display: flex;
        align-items: center;
        margin-bottom: 10px;
        padding: 1px;
        background-color: #F5F5F5;
        border-radius: 10px;

    }

    /* Style the label within the input group */
    .input-label {
        flex: 0 0 200px;
        /* Adjust the width as needed */
        font-weight: bold;
        margin-right: 10px;
        color: #A5A5A5;
    }

    /* Style the input field within the input group */
    .form-control {
        flex: 1;
        min-width: 150px;
        padding: 20px;
        border-radius: 8px;
        border: none;
        font-size: 16px;
        text-align: left;
        background-color: #F5F5F5;
    }

    /* Style the placeholder text */
    .form-control::placeholder {
        color: #A5A5A5;
        font-weight: normal;
        /* Remove bold styling for placeholder */
    }

    .columns {
        display: flex;
        justify-content: space-between;
    }

    .column {
        flex: 0 0 calc(50% - 10px);
    }
</style>



{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mentor Match</title>
    <link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet'>
    <link rel="icon" type="image/x-icon" href="{{url_for('static', filename='logo.png')}}">
</head>
<style>
    body {
        font-family: Montserrat;
        margin: 0;
        padding: 0;
    }

    .navbar {
        top: 0;
        left: 0;
        background-color: #5A110C;
        color: #FFE085;
        display: flex;
        font-size: 25px;
        justify-content: space-between;
        align-items: center;
        padding: 10px 20px;
    }

    .logo {
        display: flex;
        align-items: center;
    }

    .logo img {
        width: 15%;
        height: 15%;
        margin-right: 10px;
    }

    /* Use a div with three lines for the button */
    .nav-button {
        color: #FFE085;
        border: none;
        padding: 10px 20px;
        cursor: pointer;
        display: flex;
        flex-direction: column;
    }

    /* Style the burger lines */
    .nav-button div {
        width: 30px;
        height: 3px;
        background-color: #FFE085;
        margin: 3px 0;
    }

    .sidenav {
        width: 300px;
        background-color: #420D0A;
        height: 100%;
        position: fixed;
        top: 0;
        right: -300px;
        /* Start from the right */
        transition: right 0.3s;
        /* Change 'left' to 'right' */
    }

    .sidenav a {
        padding: 15px 25px;
        text-decoration: none;
        font-size: 18px;
        color: #FFE085;
        display: block;
    }

    .nav-user-info {
        color: #FFE085;
        font-family: Montserrat;
        display: flex;
        align-items: center;
        padding: 0px;
    }

    .circle {
        width: 30px;
        height: 30px;
        background-color: #ccc;
        border-radius: 50%;
        margin-right: 20px;
    }

    .nav-user-info p {
        font-size: 15px;
        font-family: Montserrat;
        margin: 0;
    }

    /* Add CSS for the "X" button */
    .close-button {
        position: absolute;
        top: 10px;
        right: 10px;
        font-size: 24px;
        color: #fff;
        cursor: pointer;
    }

    /* Add CSS for the Logout link */
    .logout-link {
        position: absolute;
        bottom: 10px;
        /* Adjust as needed */
        right: 10px;
        /* Adjust as needed */
        color: #fff;
        text-decoration: none;
        font-size: 18px;
    }
</style>

<body>
    <div class="navbar">
        <div class="logo">
            <img src="{{ url_for('static',filename='logo.png') }}" alt="Logo" href="{{ url_for('home.home')}}">
            <span>Mentor Match</span>
        </div>
        <!-- Use a div with three lines for the button -->
        <div class="nav-button" id="toggleNav">
            <div></div>
            <div></div>
            <div></div>
        </div>
    </div>

    <div class="sidenav" id="sideNav">
        <span class="close-button" id="closeNav" onclick="closeNav()">&times;</span>
    </br>
        <a>
            <div class="nav-user-info">
                <div class="circle"></div>
                <div>
                    <p>{{account_type[current_user.account_status]}}</p>
                    <p style="color: #fff">{{current_user.first_name + " " +current_user.last_name}}</p>
                    <p>{{current_user.program}}</p>
                </div>
            </div>
        </a>
        <a href="{{url_for('home.home')}}">Home</a>
        <a href="{{url_for('edit_profile.edit_profile')}}">Edit Profile</a>
        {% if current_user.account_status == 3 %}
        <a href="{{url_for('student_requests.my_requests')}}">My Requests</a>
        <a href="{{url_for('student_tutor_application.tutor_application')}}">Be a Tutor Now!</a>
        {% endif %}
        <a href="{{url_for('authentication.logout')}}" class="logout-link">Logout</a>
    </div>

    {% block main %}
    {% endblock %}

    <script>
        const toggleNavButton = document.getElementById('toggleNav');
        const sideNav = document.getElementById('sideNav');

        function openNav() {
            sideNav.style.right = "0"; // Slide in from the right
        }

        function closeNav() {
            sideNav.style.right = "-300px"; // Slide out to the right
        }

        toggleNavButton.addEventListener('click', openNav);

        // Close side nav when clicking outside of it
        window.addEventListener('click', (event) => {
            if (event.target === sideNav) {
                closeNav();
            }
        });
    </script>
</body>

</html>

app/templates/login.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Login</title>
  <link rel="stylesheet" href="{{url_for('static', filename='login.css')}}">
  <link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet'>
  <link rel="icon" type="image/x-icon" href="{{url_for('static', filename='logo.png')}}">
  <!--
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  -->


</head>

<body>
  <div class="container">
    <img src="{{url_for('static', filename='logo.png')}}">
    <h1>Mentor Match</h1>
    <div class="jumbotron">

      {% with messages = get_flashed_messages() %}
      {% if messages %}
      {% for message in messages %}
      <div class="alert alert-danger" role="alert">
        {{message}}
      </div>
      {% endfor %}
      {% endif %}
      {% endwith %}

      <form action="{{ url_for('authentication.login') }}" method="POST">

        {{ form.crsf_token }}

        {{ form.hidden_tag() }}
        <div class="form-group">

          {{ form.login_name(size=20, class="form-control", placeholder="LOGIN NAME") }}
        </div>

        <div class="form-group">
          {{ form.password(size=20, class="form-control", placeholder="PASSWORD",
          type="password") }}
        </div>

        <div class="text-center">
          <a href="#" style="color: #371513;"> Forgot Password?</a>
        </div>

        </br>

        <div class="text-center">
          {{ form.login(size=20, class="btn btn-success", type="submit")}}
        </div>

      </form>
    </div>
    <div class="text-center">
      <p style="color: #FFE085;">Don't have an account?<a href="{{ url_for('registration.register') }}"> Sign up here.</a></p>
    </div>


  </div>
</body>

</html>

app/templates/registration.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Register</title>
  <link rel="stylesheet" href="{{url_for('static', filename='registration.css')}}">
  <link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet'>
  <link rel="icon" type="image/x-icon" href="{{url_for('static', filename='logo.png')}}">
</head>

<body>
  <div class="container">
    <img src="{{url_for('static', filename='logo.png')}}">
    <h1>Mentor Match</h1>
    <div class="jumbotron">

      {% with messages = get_flashed_messages() %}
      {% if messages %}
      {% for message in messages %}
      <div class="alert alert-danger" role="alert">
        {{message}}
      </div>
      {% endfor %}
      {% endif %}
      {% endwith %}

      <form method="POST" action="{{ url_for('registration.register') }}">
        {{ form.hidden_tag() }}
        <div class="form-group">
          {{ form.login_name(size=20, class="form-control", placeholder="LOGIN NAME") }}
        </div>

        <div class="form-group">
          {{ form.first_name(size=20, class="form-control", placeholder="FIRST NAME") }}
        </div>

        <div class="form-group">

          {{ form.last_name(size=20, class="form-control", placeholder="LAST NAME") }}
        </div>

        <div class="form-group">
          {{ form.university_number(size=20, class="form-control", placeholder="STUDENT NUMBER") }}
        </div>

        <div class="form-group">

          {{ form.program(size=20, class="form-control", placeholder="PROGRAM") }}
        </div>

        <div class="form-group">

          {{ form.university_email(size=20, class="form-control", placeholder="EMAIL") }}
        </div>

        <div class="form-group">
          {{ form.password(size=20, class="form-control", placeholder="PASSWORD", type="password") }}
        </div>

        <div class="text-center">
          {{ form.register(size=20, class="btn btn-success", type="submit") }}
        </div>
      </form>
    </div>
    <div class="text-center">
      <p style="color: #FFE085">Already have an account? <a href="{{ url_for('authentication.login') }}">Login here.</a></p>
    </div>
  </div>
</body>

</html>